### ISSUE TITLE
Electron app issue

### ISSUE THREAD

**Issue by aaden001** [maxstue/vite-reactts-electron-starter#14]
I just tried this out and it worked on the browser but it shows a bunch of errors on the electron app itself.

![Capture](https://user-images.githubusercontent.com/25351855/141517459-2abd4513-72ce-4846-b204-81f8a546b43b.PNG)

**Comment by maxstue** [comment]
@aaden001 Thanks for creating this issue. 
I noticed that the error says something about a "Nav.tsx" file, but there ist no such file in this repository.
And I just tried ithe app from the dev branch and it works fine, in the browser end electron environment.

So could you repreoduce your steps please ? :)

**Comment by aaden001** [comment]
I apologize I got many project start-ups mixed up. It works now when I run yarn build and dev. 
But when I ran `yarn dist` i got this error

`tsc -p electron

  • electron-builder  version=22.11.7 os=10.0.19043
  • loaded configuration  file=package.json ("build" field)
  ⨯ Package "electron" is only allowed in "devDependencies". Please remove it from the "dependencies" section in your package.json.       
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

I moved electron version from dependencies to devDependencies, it built perfectly and it works! Thank you very much!
