### ISSUE TITLE
bundled files are not packaged

### ISSUE THREAD

**Issue by gwendalF** [maxstue/vite-reactts-electron-starter#18]
Hello,
I am having troubles distributing the electron app with your template. Even though the files include the out folder, the js files produced by vite are not included in the executable of the electron app. It uses my local files. If I delete these files, the application cannot load the js files. And if I use a CI/CD to build the app I cannot use the application. Any idea how to fix it? I found the electron-builder do difficult to understand.
Thanks in advance for this template anyway. I found it very useful

**Comment by maxstue** [comment]
Hi, 
Sorry for my late response.
So if you execute the ".exe" inside the dist folder it uses the dev files?
Have you tried copying the dist folder to any other location and than try to execute it.

Because I can copy the dist folder anywhere, even another pc, and I can still run the app (the ".exe"-file)

**Comment by gwendalF** [comment]
Hello,

Yes it seems to use the out folder. I can move out to a different folder it
will works but fails if I delete the out folder or use the app on another
computer, without the out folder

**Comment by gwendalF** [comment]
Hello,

Just an update on this issue. I've change the path on the index.html file produced in the out folder to be relative instead of absolute and it fixed this. I still have a missing path for the Electron icon asset since it uses my full path to the build icon and not I guess the relative one needed from the asar archive.
I guess it's a vite configuration problem?

**Comment by maxstue** [comment]
Thanks for your info and help, this should be fixed now on the main branch :)
