### ISSUE TITLE
Can'nt change title bar color

### ISSUE THREAD

**Issue by awakutu** [maxstue/vite-reactts-electron-starter#3]
Hi, i tried using custom-electron-titlebar with your starter to change title bar color but not working. Then, only displaying the white blank view. Do you have another way to do this?

![Blank](https://user-images.githubusercontent.com/43315853/113184093-fb06e600-927e-11eb-8e42-01e2f3416320.jpg)

**Comment by maxstue** [comment]
Hi @awakutu , i will have a look into it the comming days. 
Do you have a repo with your code?

**Comment by awakutu** [comment]
Sure, Sir. 

You can check in this my temporary repo (https://github.com/awakutu/grpo-desktop).

**Comment by awakutu** [comment]
Sir, i'm so sorry. I recently just found the solution.  Because can't use custom-electron-title-bar, so i think maybe if we use frameless will fix this and work. 

So, i set my electron frame to false. Then, make title bar component to make look alike title-bar electron with our styling and dragable. 

Ref: https://www.electronjs.org/docs/api/frameless-window
Ref: https://stackoverflow.com/questions/44818508/how-do-i-move-a-frameless-window-in-electron-without-using-webkit-app-region

**Comment by maxstue** [comment]
@awakutu Ah okay thanks for the information. Maybe i will add a frameless window style to this template

**Comment by awakutu** [comment]
Yes, of course. Maybe you can consider to using ipcMain and ipcRenderer too with frameless windows style.

**Comment by maxstue** [comment]
@awakutu I will have a look at it, but I'm somewhat new to the electron stuff. Maybe if you want to do it you can add it and make a PR ;) If you like to, of course
