### ISSUE TITLE
Version without TawilwindCSS?

### ISSUE THREAD

**Issue by matteoturini** [maxstue/vite-reactts-electron-starter#6]

**Comment by maxstue** [comment]
@matteoturini  What do you mean?

**Comment by matteoturini** [comment]
A template without tailwind css/postcss configuration.

Em qui., 15 de jul. de 2021 18:45, Maximilian Stümpfl <
***@***.***> escreveu:

**Comment by maxstue** [comment]
@matteoturini  This template uses tailwindcss, its just not in the newest version atm.

**Comment by matteoturini** [comment]
Yes, I know, I am asking for a version of this template WITHOUT tailwindcss/postcss. Just React, Typescript.

**Comment by maxstue** [comment]
Ouh thats what you mean. You can do that by just removing the npm packages "tailwind" and "postcss" and than removing/changing the tailwind classaes in the react files
