### ISSUE TITLE
Uncaught ReferenceError: global is not defined

### ISSUE THREAD

**Issue by dev-SR** [maxstue/vite-reactts-electron-starter#7]
How should I communicate with electron??
Below code is giving Uncaught ReferenceError: global is not defined

```javascript
function App() {
	const sendMessageToElectron = () => {
		global.ipcRenderer.send('message', 'Hello World');
	};
	return (
		<div className=' flex flex-col justify-center items-center h-screen bg-gray-800 space-y-4'>
			<button
				className='bg-yellow-400 py-2 px-4 rounded focus:outline-none shadow hover:bg-yellow-200'
				onClick={sendMessageToElectron}>
				Click Me
			</button>
		</div>
	);
}
```

**Comment by maxstue** [comment]
@dev-SR  The ipcRenderer or other electron related stuff like global isn't set up in this template. 
This template is a realy bare bone one.
If you feel like it should be in every template you can make the changes and a PR so everyone can benefit from it :)
